openapi: 3.0.1
info:
  title: API de Productos
  description: API para la gestión de productos en la tienda
  version: 1.0.0

paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '201':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/products"
        '500':
          description: Internal server error

    post:
      summary: Agrega un product
      security:
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto agregado
        '401':
          description: No autorizado
        '403':
          description: Acceso denegado

  api/products/{pid}:
    get:
      get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado

    put:
      summary: Actualizar un producto
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Producto actualizado exitosamente
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado
        '403':
          description: Acceso denegado

    delete:
      summary: Eliminar un producto
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado
        '401':
          description: No autorizado
        '403':
          description: Acceso denegado

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad en stock
        thumbnail:
          type: string
          description: The product thumbnail
        code: 
          type: string
          description: Codigo del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: The product owner

    ProductInput:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        category:
          type: string
          description: Categoría del producto
        stock:
          type: integer
          description: Cantidad en stock
      required:
        - name
        - price